version: '3.9'

services:
  app:
    build: app/.
    image: ${APP_IMAGE}
    container_name: app
    env_file:
      - .env
    volumes:
      - ${APP_SOURCE_PATH}:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    image: nginx:1.27.4-alpine
    container_name: web-proxy
    depends_on:
      - app
    ports:
      - "${WEB_PROXY_PORT_80}:80"
      - "${WEB_PROXY_PORT_443}:443"
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx:ro
      - ${NGINX_CERT_PATH}:/etc/nginx/certs:ro
    environment:
      - NGINX_HOST=localhost

  rabbitmq:
    image: rabbitmq:4.0-alpine
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT_MANAGEMENT}:15672"
      - "${RABBITMQ_PORT_QUEUE}:5672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres:16.2-alpine
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
  rabbitmq_volume:
