version: '3.9'

services:
  app:
    build: app/.
    image: ${APP_IMAGE}
    container_name: app
    env_file:
      - .env
    volumes:
      - ${APP_SOURCE_PATH}:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    image: nginx
    container_name: web-proxy
    depends_on:
      - app
    ports:
      - "${WEB_PROXY_PORT_80}:80"
      - "${WEB_PROXY_PORT_443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    environment:
      - NGINX_HOST=localhost

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT_MANAGEMENT}:15672"
      - "${RABBITMQ_PORT_QUEUE}:5672"
    volumes:
      - ${RABBITMQ_DATA_PATH}:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
